#!/bin/bash
set -e
BASE=https://cdn.jsdelivr.net/gh/dimavrodekrav-blip/vesbenzin-bot@main
mkdir -p "deploy"
mkdir -p "handlers"
mkdir -p "parsers"
mkdir -p "research"
mkdir -p "services"
curl -sf -o "deploy/deploy.sh" "$BASE/deploy/deploy.sh"
curl -sf -o "deploy/setup_env.sh" "$BASE/deploy/setup_env.sh"
curl -sf -o "deploy/vesbenzin-bot.service" "$BASE/deploy/vesbenzin-bot.service"
curl -sf -o "handlers/__init__.py" "$BASE/handlers/__init__.py"
curl -sf -o "handlers/admin.py" "$BASE/handlers/admin.py"
curl -sf -o "handlers/settings.py" "$BASE/handlers/settings.py"
curl -sf -o "handlers/user.py" "$BASE/handlers/user.py"
curl -sf -o "parsers/__init__.py" "$BASE/parsers/__init__.py"
curl -sf -o "parsers/base.py" "$BASE/parsers/base.py"
curl -sf -o "parsers/gdebenz.py" "$BASE/parsers/gdebenz.py"
curl -sf -o "parsers/pinggi.py" "$BASE/parsers/pinggi.py"
curl -sf -o "research/requirements.txt" "$BASE/research/requirements.txt"
curl -sf -o "research/run_audit.sh" "$BASE/research/run_audit.sh"
curl -sf -o "research/setup_tg.sh" "$BASE/research/setup_tg.sh"
curl -sf -o "research/telegram_audit.py" "$BASE/research/telegram_audit.py"
curl -sf -o "services/notifier.py" "$BASE/services/notifier.py"
curl -sf -o "services/poller.py" "$BASE/services/poller.py"
curl -sf -o "services/status_mapper.py" "$BASE/services/status_mapper.py"
curl -sf -o ".env.example" "$BASE/.env.example"
curl -sf -o ".gitignore" "$BASE/.gitignore"
curl -sf -o "bot.py" "$BASE/bot.py"
curl -sf -o "config.py" "$BASE/config.py"
curl -sf -o "constants.py" "$BASE/constants.py"
curl -sf -o "database.py" "$BASE/database.py"
curl -sf -o "keyboards.py" "$BASE/keyboards.py"
curl -sf -o "main.py" "$BASE/main.py"
curl -sf -o "README.md" "$BASE/README.md"
curl -sf -o "requirements.txt" "$BASE/requirements.txt"
curl -sf -o "states.py" "$BASE/states.py"
echo "DONE: $(find . -type f | wc -l) files"
